Update to us python 3.8
The SAM build is failing..

```
➜  sam build
Building codeuri: /Users/zaro0508/work-sage/s3-synapse-sync/s3_synapse_sync runtime:
  python3.6 metadata: {} functions: ['Function']

Build Failed
Error: PythonPipBuilder:Validation - Binary validation failed for python, searched
  for python in following locations  : ['/usr/local/var/pyenv/shims/python3.6',
  '/usr/local/var/pyenv/shims/python', '/usr/bin/python'] which did not satisfy
  constraints for runtime: python3.6. Do you have python for runtime: python3.6 on
  your PATH?
```

I believe this means that AWS has stopped supporting python 3.6. We need
to update this project to use a more recent version of python so we are
updating to pythobn 3.8.