fix SAM build failure
SAM build command was failing..

```
$ sam build
Building function 'Function'
Running PythonPipBuilder:ResolveDependencies
Build Failed
Error: PythonPipBuilder:ResolveDependencies - {pyyaml==6.0(wheel), cryptography==35.0.0(wheel), cffi==1.15.0(wheel)}
The command "sam build" exited with 1.
```

This is due to some change with wheels[1].  We attempt to pip
install wheel as a fix.

[1] https://github.com/aws/aws-lambda-builders/issues/280