fix SAM build failure
SAM build command was failing..

```
$ sam build
Building function 'Function'
Running PythonPipBuilder:ResolveDependencies
Build Failed
Error: PythonPipBuilder:ResolveDependencies - {pyyaml==6.0(wheel), cryptography==35.0.0(wheel), cffi==1.15.0(wheel)}
The command "sam build" exited with 1.
```

This is probably because something changed with SAM that it
expected better defined dependencies.